SoourceCode/sb-admin-2.Web/Controllers/ManageMarketingController.cs
using ICSharpCode.SharpZipLib.Zip;
using OfficeOpenXml;
using sb_admin_2.Web.Models;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace sb_admin_2.Web.Controllers
{
    public class ManageMarketingController : Controller
    {
        DBModel db = new DBModel();
        // GET: ManageMarketing
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AddFaculty()
        {
            return View();
        }
        [HttpPost]
        public ActionResult AddFaculty_Detail(String facultyname, String description)
        {
            try
            {
                Faculty fac = new Faculty();
                fac.FacultyName = facultyname;
                fac.Description = description;
                db.Faculties.Add(fac);
                db.SaveChanges();
                ViewBag.Success = "Add faculty Successfully!";
                return View("AddFaculty");
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public void displayDropDL()
        {
            List<Faculty> listFac = db.Faculties.ToList();
            ViewBag.listFac = new SelectList(listFac, "FacultyID", "FacultyName");
            string role = "Marketing Coordinator";
            var listMC = from u in db.Users
                         where (u.Role1.RoleName == role)
                         select u; // select all role manage coordinator
            ViewBag.listMC = new SelectList(listMC, "UserID", "Name");
        }

        public ActionResult Assigned_Faculty()
        {
            try
            {
                displayDropDL();
                return View();
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult Assigned_Faculty_Detail(String FacultyID, String UserID)
        {
            try
            {
                String Fac = FacultyID.ToUpper();
                String Use = UserID.ToUpper();
                var FacultyID_ToUpper = Guid.Parse(Fac);
                var UserID_ToUpper = Guid.Parse(Use);
                //Faculty faculty = db.Faculties.SingleOrDefault(f => f.FacultyID.Equals(FacultyID_ToUpper));
                //Faculty_Detail fd = db.Faculty_Detail.SingleOrDefault(f => f.FacultyID.Equals(FacultyID_ToUpper));
                var fd = from f in db.Faculty_Detail
                         where (f.FacultyID == FacultyID_ToUpper)
                         select f;
                if (fd.Count() == 0)
                {
                    Faculty_Detail faculty_Detail = new Faculty_Detail();
                    faculty_Detail.FacultyID = FacultyID_ToUpper;
                    faculty_Detail.UserCoordinator = UserID_ToUpper;
                    db.Faculty_Detail.Add(faculty_Detail);
                    db.SaveChanges();
                    ViewBag.Success = "Assigned Faculty Successfully!";
                }
                else
                {
                    ViewBag.Error = "This faculty was assigned!";
                }
                displayDropDL();
                return View("Assigned_Faculty");
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        //View All faculty
        public ActionResult View_All_Faculty()
        {
            try
            {
                List<Faculty> listFac = db.Faculties.ToList();
                List<int> countDocument = new List<int>();
                for (int i = 0; i < listFac.Count; i++)
                {
                    var facId = Guid.Parse(listFac[i].FacultyID.ToString());
                    var count = (from ct in db.Categories
                                 join ctb in db.Contributions
                                 on ct.CategoryID equals ctb.Category
                                 join fd1 in db.Faculty_Detail
                                 on ct.Faculty_DetailID equals fd1.Faculty_DetailID
                                 join f1 in db.Faculties
                                 on fd1.FacultyID equals f1.FacultyID
                                 where (ct.CategoryID == ctb.Category && ct.Faculty_DetailID == fd1.Faculty_DetailID
                                 && f1.FacultyID == fd1.FacultyID
                                 && f1.FacultyID == facId)
                                 select ctb).Count();
                    countDocument.Add(count);
                }
                ViewBag.countDocument = countDocument;
                return View(listFac);
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult View_Detail_Faculty(String FacultyID)
        {
            try
            {
                var facId = Guid.Parse(FacultyID);
                Faculty_Detail faculty_Detail = db.Faculty_Detail.SingleOrDefault(facd => facd.FacultyID == facId);
                var listCTB = from ct in db.Categories
                              join ctb in db.Contributions
                              on ct.CategoryID equals ctb.Category
                              join fd1 in db.Faculty_Detail
                              on ct.Faculty_DetailID equals fd1.Faculty_DetailID
                              join f1 in db.Faculties
                              on fd1.FacultyID equals f1.FacultyID
                              where (ct.CategoryID == ctb.Category && ct.Faculty_DetailID == fd1.Faculty_DetailID
                              && f1.FacultyID == fd1.FacultyID
                              && fd1.Faculty_DetailID == faculty_Detail.Faculty_DetailID)
                              select ctb;
                return View(listCTB.ToList());
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult View_Detail_Document(String ContributionID)
        {
            try
            {
                var ContributionID_Guid = Guid.Parse(ContributionID);
                MultipleModelInOneView_List ml = new MultipleModelInOneView_List();
                List<Document> listDoc = db.Documents.Where(dc => dc.Contribution == ContributionID_Guid).ToList();
                List<Image> listImg = db.Images.Where(im => im.Contribution == ContributionID_Guid).ToList();
                List<Comment> listCmt = db.Comments.Where(im => im.Contribution == ContributionID_Guid && im.Status == 1).ToList();
                List<User> listUser = new List<User>();
                for (int i = 0; i < listCmt.Count; i++)
                {
                    var user_t = listCmt[i].Creator;
                    User user1 = db.Users.SingleOrDefault(us => us.UserID == user_t);
                    listUser.Add(user1);
                }
                ml.users = listUser;
                ml.documents = listDoc;
                ml.images = listImg;
                ml.comments = listCmt;
                ViewBag.ContributionID = ContributionID;
                return View(ml);
            }
            catch(Exception e)
            {
                return View("Error");
            }
            
        }
        // Download Zip file
        public ActionResult Download_ZipFiles(String ContributionID)
        {
            try
            {
                List<String> allFilePath = new List<string>();
                var ContributionID_Guid = Guid.Parse(ContributionID);
                Contribution contribution = db.Contributions.SingleOrDefault(ctb => ctb.ContributionID == ContributionID_Guid);
                List<Document> list_Document = db.Documents.Where(dc => dc.Contribution == ContributionID_Guid).ToList();
                for (int i = 0; i < list_Document.Count; i++)
                {
                    allFilePath.Add(Path.Combine(Server.MapPath("~/Files/"), list_Document[i].Path.Replace("~/Files/", "")));
                }
                List<Image> list_Image = db.Images.Where(im => im.Contribution == ContributionID_Guid).ToList();
                for (int j = 0; j < list_Image.Count; j++)
                {
                    allFilePath.Add(Path.Combine(Server.MapPath("~/Images/"), list_Image[j].Path.Replace("~/Images/", "")));
                }
                string zipFileName = contribution.Category1.CategoryName + ".zip";
                Response.ContentType = "application/zip";
                Response.AddHeader("content-disposition", "filename=" + zipFileName);
                byte[] buffer = new byte[4096];
                ZipOutputStream zipOutputStream = new ZipOutputStream(Response.OutputStream);
                zipOutputStream.SetLevel(3);
                try
                {
                    for (int k = 0; k < allFilePath.Count; k++)
                    {
                        Stream fs = System.IO.File.OpenRead(allFilePath[k]);
                        ZipEntry zipEntry = new ZipEntry(ZipEntry.CleanName(Path.GetFileName(allFilePath[k])));
                        zipEntry.Size = fs.Length;
                        zipOutputStream.PutNextEntry(zipEntry);
                        int count = fs.Read(buffer, 0, buffer.Length);
                        while (count > 0)
                        {
                            zipOutputStream.Write(buffer, 0, count);
                            count = fs.Read(buffer, 0, buffer.Length);
                            if (!Response.IsClientConnected)
                            {
                                break;
                            }
                            Response.Flush();
                        }
                        fs.Close();
                    }

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/AddFaculty.cshtml
@{
    ViewBag.Title = "AddFaculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Login</title>

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add Faculty</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="width: 50%; margin: auto;">
            <form id="form" method="post" action="@Url.Action("AddFaculty_Detail", "ManageMarketing")">
                <div class="form-group">
                    <label>Faculty Name</label>
                    <input class="form-control" type="text" id="facultyname" name="facultyname" required placeholder="Faculty name">
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" id="description" name="description" required placeholder="Description" rows="5"></textarea>
                </div>
                <button class="btn btn-default btn-primary">Add Faculty</button>
            </form>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/Assigned_Faculty.cshtml
@{
    ViewBag.Title = "Assigned_Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Assigned Faculty</title>

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    @if (@ViewBag.Error != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Error
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Assigned Faculty</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="width: 50%; margin: auto;">
            <form id="form" method="post" action="@Url.Action("Assigned_Faculty_Detail", "ManageMarketing")">
                <div class="form-group">
                    <label>Faculty Name</label>
                    @Html.DropDownList("FacultyID", ViewBag.listFac as SelectList, "---Select Faculty---", htmlAttributes: new { @class = "form-control", @required = "true", @name = "FacultyID", @id = "FacultyID" })
                </div>

                <div class="form-group">
                    <label>ManageCoordinator</label>
                    @Html.DropDownList("UserID", ViewBag.listMC as SelectList, "---Select ManageCoordinator---", htmlAttributes: new { @class = "form-control", @required = "true", @name = "UserID", @id = "FacultyID" })
                </div>

                <button class="btn btn-default btn-primary">Assigned Faculty</button>
            </form>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/Create_Guest_Account.cshtml
@{
    ViewBag.Title = "Create_Guest_Account";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    @if (@ViewBag.Error != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Error
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Create Account</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="width: 50%; margin: auto; margin-bottom: 3%;">
            <form id="form" method="post" action="@Url.Action("Created_Guest_Account_Detail", "ManageMarketing")">
                <div class="form-group">
                    <label>Email</label>
                    <input class="form-control" type="text" id="email" name="email" required placeholder="Enter Your Email">
                    <p style="color: red;">Note: Email you should enter same: exactlyemail@gmail.com</p>
                </div>
                <div class="form-group">
                    <label>Password</label>
                    <input class="form-control" type="password" id="password" name="password" required placeholder="Enter Your Password">
                </div>
                <div class="form-group">
                    <label>Name</label>
                    <input class="form-control" type="text" id="name" name="name" required placeholder="Enter Your Name">
                </div>
                <div class="form-group">
                    <label>Address</label>
                    <input class="form-control" type="text" id="address" name="address" required placeholder="Enter Your Address">
                </div>
                <div class="form-group">
                    <label>Phone</label>
                    <input class="form-control" type="number" id="phone" name="phone" required placeholder="Enter Your Phone">
                    <p style="color: red;">Note: Phone is number and start equal 0 and 9 character continue</p>
                </div>
                <div class="form-group">
                    <label>Choose Role</label>
                    @Html.DropDownList("RoleID", ViewBag.listRole as SelectList, "---Select Role---", htmlAttributes: new { @class = "form-control", @required = "true", @name = "RoleID", @id = "RoleID" })
                </div>
                <button class="btn btn-default btn-primary">Create Account</button>
            </form>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/View_All_Faculty.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Faculty>
@{
    ViewBag.Title = "View_All_Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">All Faculties</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        @{int i = 0; }
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-files-o"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div style="font-size: 15px; color: #f36868;">@ViewBag.countDocument[i]</div>
                                <div>@item.FacultyName</div>
                            </div>
                        </div>
                    </div>
                    @if (item.Faculty_Detail.Count == 0)
                    {
                        <div class="panel-footer">
                            <span class="pull-left">Not yet assigned</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    }
                    else
                    {
                        <a href="@Url.Action("View_Detail_Faculty", "ManageMarketing", new { FacultyID = item.FacultyID })">
                            <div class="panel-footer">
                                <span class="pull-left">View Details</span>
                                <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                                <div class="clearfix"></div>
                            </div>
                        </a>
                    }
                </div>
            </div>
            i++;
        }
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/View_Detail_Faculty.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Contribution>
@{
    ViewBag.Title = "View_Detail_Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contributions in Faculties</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    DataTables Contributions
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>UserName</th>
                                    <th>Category</th>
                                    <th>Title</th>
                                    <th>Final Closure Date</th>
                                    <th>Document</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td>@item.User.Name</td>
                                        <td>@item.Category1.CategoryName</td>
                                        <td>@item.Title</td>
                                        <td class="center">@item.Category1.FinalClosureDate</td>
                                        <td class="center">@item.Documents.Count</td>
                                        <td class="center">@item.Images.Count</td>
                                        <td class="center">
                                            <a href="@Url.Action("View_Detail_Document", "ManageMarketing", new { ContributionID = item.ContributionID })" class="fa fa-folder-open-o" style="font-size: 24px;"></a>
                                            @if (item.Status == 1)
                                            {
                                                <a href="#" class="fa fa-lock" style="font-size: 24px; float: right;"></a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("Download_ZipFiles", "ManageMarketing", new { ContributionID = item.ContributionID })" class="fa fa-download" style="font-size: 24px; float: right;"></a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageMarketing/View_Statistic.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Contribution>
@{
    ViewBag.Title = "View_Statistic";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Add Category</title>

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    @if (@ViewBag.Error != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Error
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <form id="form" method="post" action="@Url.Action("Search_Statistic", "ManageMarketing")">
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>From date</label>
                        <input class="form-control" type="date" name="fromdate" id="fromdate" value="@ViewBag.fromdate" required />
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="form-group">
                        <label>To date</label>
                        <input class="form-control" type="date" value="@ViewBag.todate" name="todate" id="todate" required />
                    </div>
                </div>
                <div class="col-lg-2">
                    <label style="color: white;">button</label><br />
                    <button class="btn btn-default btn-primary" style="width: 100%;">Search</button>
                </div>
                <div class="col-lg-2">
                    <label style="color: white;">button</label><br />
                    <a href="@Url.Action("ExportToExcel", "ManageMarketing", new { fromdate = ViewBag.fromdate, todate = ViewBag.todate})" class="btn btn-default btn-primary">Export To Excel</a>
                </div>
            </form>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    DataTables Contributions <span style="float: right;">Total Contributions: @Model.Count()</span>
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>UserName</th>
                                    <th>Category</th>
                                    <th>Title</th>
                                    <th>Final Closure Date</th>
                                    <th>Document</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td>@item.User.Name</td>
                                        <td>@item.Category1.CategoryName</td>
                                        <td>@item.Title</td>
                                        <td class="center">@item.Category1.FinalClosureDate</td>
                                        <td class="center">@item.Documents.Count</td>
                                        <td class="center">@item.Images.Count</td>
                                        <td class="center">
                                            <a href="@Url.Action("View_Detail_Document", "ManageMarketing", new { ContributionID = item.ContributionID })" class="fa fa-folder-open-o" style="font-size: 24px;"></a>
                                            @if (item.Status == 1)
                                            {
                                                <a href="#" class="fa fa-lock" style="font-size: 24px; float: right;"></a>
                                            }
                                            else
                                            {
                                                <a href="@Url.Action("Download_ZipFiles", "ManageMarketing", new { ContributionID = item.ContributionID })" class="fa fa-download" style="font-size: 24px; float: right;"></a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</body>
</html>