SoourceCode/sb-admin-2.Web/Controllers/ManageCoordinatorController.cs
using sb_admin_2.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace sb_admin_2.Web.Controllers
{
    public class ManageCoordinatorController : Controller
    {
        DBModel db = new DBModel();
        // GET: ManageCoordinator
        public ActionResult Index()
        {
            return View();
        }

        private void displayFacId()
        {
            User user = (User)Session["User"];
            var abc = from f in db.Faculties
                      join fd in db.Faculty_Detail
                      on f.FacultyID equals fd.FacultyID
                      where (f.FacultyID == fd.FacultyID && fd.User.UserID == user.UserID)
                      select f;
            List<Faculty> listFac = abc.ToList();
            ViewBag.listFac = new SelectList(listFac, "FacultyID", "FacultyName");
        }

        public ActionResult Add_Category()
        {
            try
            {
                displayFacId();
                return View();
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult Add_Category_Detail(String categoryname, String closuredate, String finalclosuredate, String FacultyID, String description)
        {
            try
            {
                User user = (User)Session["User"];
                String Fac = FacultyID.ToUpper();
                var FacultyID_ToUpper = Guid.Parse(Fac);
                DateTime datenow = DateTime.Now.Date;
                DateTime cld = DateTime.Parse(closuredate).Date;
                DateTime fnd = DateTime.Parse(finalclosuredate).Date;
                DateTime ClosureDate = DateTime.ParseExact(closuredate, "yyyy-MM-ddTHH:mm", null);
                DateTime FinalClosureDate = DateTime.ParseExact(finalclosuredate, "yyyy-MM-ddTHH:mm", null);
                Faculty_Detail faculty_Detail = db.Faculty_Detail.SingleOrDefault(fd => fd.FacultyID == FacultyID_ToUpper && fd.UserCoordinator == user.UserID);
                var cat = from c in db.Categories
                          where (c.Faculty_Detail.FacultyID == FacultyID_ToUpper && c.CategoryName == categoryname)
                          select c;
                if (cat.Count() == 0)
                {
                    if (datenow.CompareTo(cld) <= 0)
                    {
                        if (cld.CompareTo(fnd) < 0)
                        {
                            Category category = new Category();
                            category.CategoryName = categoryname;
                            category.ClosureDate = ClosureDate;
                            category.FinalClosureDate = FinalClosureDate;
                            category.Description = description;
                            category.Status = 1;
                            category.Faculty_DetailID = faculty_Detail.Faculty_DetailID;
                            db.Categories.Add(category);
                            db.SaveChanges();
                            ViewBag.Success = "Add Category Successfully!";
                        }
                        else
                        {
                            ViewBag.Error = "Final closure date always more closure date!";
                        }
                    }
                    else
                    {
                        ViewBag.Error = "Closure date always more than or equal date now!" + cld + " das " + datenow;
                    }
                }
                else
                {
                    ViewBag.Error = "This Category is exist already!";
                }
                displayFacId();
                return View("Add_Category");
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult View_Faculty()
        {
            try
            {
                User user = (User)Session["User"];
                var abc = from f in db.Faculties
                          join fd in db.Faculty_Detail
                          on f.FacultyID equals fd.FacultyID
                          where (f.FacultyID == fd.FacultyID && fd.User.UserID == user.UserID)
                          select fd;
                List<Faculty_Detail> listFacd = abc.ToList();
                List<int> countDocument = new List<int>();
                for (int i = 0; i < listFacd.Count; i++)
                {
                    var facdId1 = Guid.Parse(listFacd[i].Faculty_DetailID.ToString());
                    var count = (from ct in db.Categories
                                 join ctb in db.Contributions
                                 on ct.CategoryID equals ctb.Category
                                 join fd1 in db.Faculty_Detail
                                 on ct.Faculty_DetailID equals fd1.Faculty_DetailID
                                 join f1 in db.Faculties
                                 on fd1.FacultyID equals f1.FacultyID
                                 where (ct.CategoryID == ctb.Category && ct.Faculty_DetailID == fd1.Faculty_DetailID
                                 && f1.FacultyID == fd1.FacultyID && fd1.UserCoordinator == user.UserID
                                 && fd1.Faculty_DetailID == facdId1)
                                 select ctb).Count();
                    countDocument.Add(count);
                }
                ViewBag.countDocument = countDocument;
                return View(listFacd);
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult View_Detail_Faculty(String Faculty_DetailID)
        {
            try
            {
                User user = (User)Session["User"];
                var facdId = Guid.Parse(Faculty_DetailID);
                var listCTB = from ct in db.Categories
                              join ctb in db.Contributions
                              on ct.CategoryID equals ctb.Category
                              join fd1 in db.Faculty_Detail
                              on ct.Faculty_DetailID equals fd1.Faculty_DetailID
                              join f1 in db.Faculties
                              on fd1.FacultyID equals f1.FacultyID
                              where (ct.CategoryID == ctb.Category && ct.Faculty_DetailID == fd1.Faculty_DetailID
                              && f1.FacultyID == fd1.FacultyID && fd1.UserCoordinator == user.UserID
                              && fd1.Faculty_DetailID == facdId)
                              select ctb;
                return View(listCTB.ToList());
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult View_Detail_Document(String ContributionID)
        {
            try
            {
                var ContributionID_Guid = Guid.Parse(ContributionID);
                MultipleModelInOneView_List ml = new MultipleModelInOneView_List();
                List<Document> listDoc = db.Documents.Where(dc => dc.Contribution == ContributionID_Guid).ToList();
                List<Image> listImg = db.Images.Where(im => im.Contribution == ContributionID_Guid).ToList();
                List<Comment> listCmt = db.Comments.Where(im => im.Contribution == ContributionID_Guid && im.Status == 1).ToList();
                List<User> listUser = new List<User>();
                for (int i = 0; i < listCmt.Count; i++)
                {
                    var user_t = listCmt[i].Creator;
                    User user1 = db.Users.SingleOrDefault(us => us.UserID == user_t);
                    listUser.Add(user1);
                }
                ml.users = listUser;
                ml.documents = listDoc;
                ml.images = listImg;
                ml.comments = listCmt;
                ViewBag.ContributionID = ContributionID;
                return View(ml);
            }
            catch (Exception e)
            {
                return View("Error");
            }
        }

        public ActionResult Add_Comment(String ContributionID, String comment)
        {
            try
            {
                User user = (User)Session["User"];
                var ContributionID_Guid = Guid.Parse(ContributionID);
                DateTime now = DateTime.Now;
                Comment comm = new Comment();
                comm.Content = comment;
                comm.Creator = user.UserID;
                comm.Contribution = ContributionID_Guid;
                comm.CommentDate = now;
                comm.Status = 1;
                db.Comments.Add(comm);
                db.SaveChanges();
                // View
                MultipleModelInOneView_List ml = new MultipleModelInOneView_List();
                List<Document> listDoc = db.Documents.Where(dc => dc.Contribution == ContributionID_Guid).ToList();
                List<Image> listImg = db.Images.Where(im => im.Contribution == ContributionID_Guid).ToList();
                List<Comment> listCmt = db.Comments.Where(im => im.Contribution == ContributionID_Guid && im.Status == 1).ToList();
                List<User> listUser = new List<User>();
                for (int i = 0; i < listCmt.Count; i++)
                {
                    var user_t = listCmt[i].Creator;
                    User user1 = db.Users.SingleOrDefault(us => us.UserID == user_t);
                    listUser.Add(user1);
                }
                ml.users = listUser;
                ml.documents = listDoc;
                ml.images = listImg;
                ml.comments = listCmt;
                ViewBag.ContributionID = ContributionID;
                return View("View_Detail_Document", ml);
            }
            catch(Exception e)
            {
                return View("Error");
            }
        }

SoourceCode/sb-admin-2.Web/Views/ManageCoordinator/Add_Category.cshtml
@{
    ViewBag.Title = "Add_Category";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Add Category</title>

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    @if (@ViewBag.Error != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Error
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Add Category</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="width: 50%; margin: auto; margin-bottom: 3%;">
            <form id="form" method="post" action="@Url.Action("Add_Category_Detail", "ManageCoordinator")">
                <div class="form-group">
                    <label>Category Name</label>
                    <input class="form-control" type="text" id="categoryname" name="categoryname" required placeholder="Category name">
                </div>
                <div class="form-group">
                    <label>Closure Date</label>
                    <input class="form-control" type="datetime-local" id="closuredate" name="closuredate" required placeholder="dd/MM/yyyy hh:mm tt">
                </div>
                <div class="form-group">
                    <label>Final Closure Date</label>
                    <input class="form-control" type="datetime-local" id="finalclosuredate" name="finalclosuredate" required placeholder="dd/MM/yyyy hh:mm tt">
                </div>
                <div class="form-group">
                    <label>Faculty Name</label>
                    @Html.DropDownList("FacultyID", ViewBag.listFac as SelectList, "---Select Faculty---", htmlAttributes: new { @class = "form-control", @required = "true", @name = "FacultyID", @id = "FacultyID" })
                </div>
                <div class="form-group">
                    <label>Description</label>
                    <textarea class="form-control" id="description" name="description" required placeholder="Description" rows="5"></textarea>
                </div>
                <button class="btn btn-default btn-primary">Add Category</button>
            </form>
        </div>
        <!-- /.col-lg-12 -->
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageCoordinator/Update_ClosureDate.cshtml
@{
    ViewBag.Title = "Update_ClosureDate";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>Add Category</title>

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <script>
        $(document).ready(function () {
            $('#CategoryID').change(function () {
                var CategoryID = $('#CategoryID').val();
                if (CategoryID == "") {
                    $('#div1').hide("slide");
                    $('#div2').hide("slide");
                    $('#btn1').hide("slide");
                } else {
                    var array = @Html.Raw(Json.Encode(((IEnumerable<sb_admin_2.Web.Models.Category>)ViewBag.ListCat_Check).Select(cat => new 
                        { 
                            catId = cat.CategoryID, 
                            catName = cat.CategoryName, 
                            catClosureDate = cat.ClosureDate.ToString(),
                            catFinalClosureDate = cat.FinalClosureDate.ToString(),
                            catFacultyID = cat.Faculty_DetailID,
                            catDescription = cat.Description,
                            catStatus = cat.Status
                        }))
                    );
                    for (var i = 0; i < array.length; i++){
                        if (CategoryID == array[i].catId) {
                            $('#oldfinalclosuredate').val(array[i].catFinalClosureDate);
                        }
                    }
                    $('#div1').show("slide");
                    $('#div2').show("slide");
                    $('#btn1').show("slide");
                }
            });
        });
    </script>

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    @if (@ViewBag.Error != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-warning alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Error
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Update Closure Date</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12" style="width: 50%; margin: auto; margin-bottom: 3%;">
            <form id="form" method="post" action="@Url.Action("Update_ClosureDate_Real", "ManageCoordinator")">
                <div class="form-group">
                    <label>Category Name</label>
                    @Html.DropDownList("CategoryID", ViewBag.listCat as SelectList, "---Select Category---", htmlAttributes: new { @class = "form-control", @required = "true", @name = "CategoryID", @id = "CategoryID" })
                </div>
                <div class="form-group" id="div1" style="display: none;">
                    <label>Old Final Closure Date</label>
                    <input class="form-control" type="text" id="oldfinalclosuredate" readonly name="oldfinalclosuredate">
                </div>
                <div class="form-group" id="div2" style="display: none;">
                    <label>New Final Closure Date</label>
                    <input class="form-control" type="datetime-local" id="new_finalclosuredate" name="new_finalclosuredate" required placeholder="dd/MM/yyyy hh:mm tt">
                </div>
                <button class="btn btn-default btn-primary" style="display: none;" id="btn1">Change Closure Date</button>
            </form>
        </div>
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageCoordinator/View_Detail_Document.cshtml
@model sb_admin_2.Web.Models.MultipleModelInOneView_List
@{
    ViewBag.Title = "View_Detail_Document";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Documents and Images in Contribution</h1>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Table Images
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>Image</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var img in Model.images)
                                {
                                    <tr>
                                        <td><img src="@Url.Content(img.Path)" style="width: 100px; height: 100px;" /></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-lg-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Table Documents
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Document</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var doc in Model.documents)
                                {
                                    <tr>
                                        <td><a href="@Url.Action("Download", "Student", new { DocumentID = doc.DocumentID })">@doc.Path.Replace("~/Files/", "")</a></td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Old Comments
                </div>
                <div class="panel-body">
                    <div class="col-lg-2">
                        @foreach (var user in Model.users)
                        {
                            <b>@user.Name (said): </b><br />
                        }
                    </div>

                    @foreach (var comment in Model.comments)
                    {
                        <div class="col-lg-7">
                            @comment.Content<br />
                        </div>
                        <div class="col-lg-3">
                            @comment.CommentDate<br />
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <form id="form" method="post" action="@Url.Action("Add_Comment", "ManageCoordinator")">
        <input hidden type="text" id="ContributionID" name="ContributionID" value="@ViewBag.ContributionID" />
        <div class="row">
            <div class="col-lg-12">
                <textarea class="form-control" rows="3" required placeholder="Enter your comment..." id="comment" name="comment"></textarea>
            </div>
        </div>
        <div class="row" style="margin-top: 2%; margin-bottom: 2%;">
            <div class="col-lg-3">
                <button class="btn btn-primary">Add Comment</button>
            </div>
        </div>
    </form>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageCoordinator/View_Detail_Faculty.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Contribution>
@{
    ViewBag.Title = "View_Detail_Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    @if (@ViewBag.Success != null)
    {
        <div style="width: 30%; margin:auto; margin-top: 2%;" class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            @ViewBag.Success
        </div>
    }
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">Contributions in Faculties</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">
                    DataTables Contributions
                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                                <tr>
                                    <th>UserName</th>
                                    <th>Category</th>
                                    <th>Title</th>
                                    <th>Final Closure Date</th>
                                    <th>Document</th>
                                    <th>Image</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr class="odd gradeX">
                                        <td>@item.User.Name</td>
                                        <td>@item.Category1.CategoryName</td>
                                        <td>@item.Title</td>
                                        <td class="center">@item.Category1.FinalClosureDate</td>
                                        <td class="center">@item.Documents.Count</td>
                                        <td class="center">@item.Images.Count</td>
                                        <td class="center">
                                            <a href="@Url.Action("View_Detail_Document", "ManageCoordinator", new { ContributionID = item.ContributionID })" class="fa fa-folder-open-o" style="font-size: 24px;"></a>
                                            @if (item.Status == 1)
                                            {
                                                <a href="@Url.Action("Publish", "ManageCoordinator", new { Faculty_DetailID = item.Category1.Faculty_DetailID, ContributionID = item.ContributionID })" class="fa fa-lock" style="font-size: 24px; float: right;"></a>
                                            }
                                            else
                                            {
                                                <a href="#" class="fa fa-unlock" style="font-size: 24px; float: right;"></a>
                                            }
                                        </td>
                                    </tr>
                                }
                            </tbody>
                        </table>
                    </div>
                </div>
                <!-- /.panel-body -->
            </div>
            <!-- /.panel -->
        </div>
    </div>
</body>
</html>

SoourceCode/sb-admin-2.Web/Views/ManageCoordinator/View_Faculty.cshtml
@model IEnumerable<sb_admin_2.Web.Models.Faculty_Detail>
@{
    ViewBag.Title = "View_Faculty";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="stylesheet" type="text/css" href="~/bower_components/bootstrap/dist/css/bootstrap.min.css" />

    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

</head>

<body>
    <div class="row">
        <div class="col-lg-12">
            <h1 class="page-header">My Faculties</h1>
        </div>
        <!-- /.col-lg-12 -->
    </div>
    <div class="row">
        @{int i = 0; }
        @foreach (var item in Model)
        {
            <div class="col-lg-3 col-md-6">
                <div class="panel panel-primary">
                    <div class="panel-heading">
                        <div class="row">
                            <div class="col-xs-3">
                                <i class="fa fa-lock"></i>
                            </div>
                            <div class="col-xs-9 text-right">
                                <div style="font-size: 15px; color: #f36868;">@ViewBag.countDocument[i]</div>
                                <div>@item.Faculty.FacultyName</div>
                            </div>
                        </div>
                    </div>
                    <a href="@Url.Action("View_Detail_Faculty", "ManageCoordinator", new { Faculty_DetailID = item.Faculty_DetailID })">
                        <div class="panel-footer">
                            <span class="pull-left">View Details</span>
                            <span class="pull-right"><i class="fa fa-arrow-circle-right"></i></span>
                            <div class="clearfix"></div>
                        </div>
                    </a>
                </div>
            </div>
            i++;
        }
    </div>
</body>
</html>